"""Build docs/TYPICAL_VS_TOTAL_PROFIT.md — a plain-language, detailed explainer of the difference
between "typical profit" (median walk-forward fold P/L) and "total profit" (full-history P/L),
grounded in the REAL 4h champion numbers, with inline Plotly + a Mermaid diagram.

Run:  python3 docs/charts/build_profit_doc.py
"""
from __future__ import annotations

import csv
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_DOCS = os.path.abspath(os.path.join(_HERE, ".."))
_ROOT = os.path.abspath(os.path.join(_DOCS, ".."))

import plotly.graph_objects as go  # noqa: E402

# Real 4h champion, recomputed from the study DB (see commit message / chat):
FOLDS = [("fold 1\nApr–Jul 25", -4738), ("fold 2\nJul–Oct 25", 23267),
         ("fold 3\nOct 25–Feb 26", 43350), ("fold 4\nFeb–May 26", 25238)]
MEDIAN = 24253      # typical profit  (median of the 4 fold P/Ls)
TOTAL = 56040       # total profit    (single continuous full-history backtest)
SUM_FOLDS = sum(v for _, v in FOLDS)   # 87,117 — deliberately NOT equal to TOTAL


def fig_folds():
    xs = [f for f, _ in FOLDS]; ys = [v for _, v in FOLDS]
    colors = ["#c62828" if v < 0 else "#5472d3" for v in ys]
    fig = go.Figure(go.Bar(x=xs, y=ys, marker_color=colors,
                           text=[f"${v:,.0f}" for v in ys], textposition="outside"))
    fig.add_hline(y=MEDIAN, line_dash="dash", line_color="#2e7d32",
                  annotation_text=f"median = TYPICAL profit ${MEDIAN:,.0f}",
                  annotation_position="top left")
    fig.update_layout(
        title="4h champion — profit in each ~3-month fold (the median is the 'typical' number)",
        yaxis_title="fold P/L ($)", margin=dict(l=10, r=20, t=50, b=60), height=440,
        plot_bgcolor="white", yaxis=dict(gridcolor="rgba(0,0,0,0.08)", zeroline=True,
                                         zerolinecolor="#999"))
    return fig


def fig_compare():
    labels = ["TYPICAL\n(median fold)", "sum of the\n4 folds", "TOTAL\n(full history, 1 run)"]
    vals = [MEDIAN, SUM_FOLDS, TOTAL]
    colors = ["#2e7d32", "#bbb", "#5472d3"]
    fig = go.Figure(go.Bar(x=labels, y=vals, marker_color=colors,
                           text=[f"${v:,.0f}" for v in vals], textposition="outside"))
    fig.update_layout(
        title="Why TOTAL ≠ TYPICAL × 5, and TOTAL ≠ sum-of-folds",
        yaxis_title="P/L ($)", margin=dict(l=10, r=20, t=50, b=50), height=420,
        plot_bgcolor="white", yaxis=dict(gridcolor="rgba(0,0,0,0.08)"))
    return fig


def _inline(fig, first):
    return fig.to_html(full_html=False, include_plotlyjs=("cdn" if first else False),
                       default_width="100%", default_height="440px")


def _leaderboard_rows():
    path = os.path.join(_ROOT, "optimize/results/wsi_leaderboard.csv")
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def main():
    f1 = _inline(fig_folds(), True)
    f2 = _inline(fig_compare(), False)
    rows = _leaderboard_rows()
    tf_table = ["| TF | TYPICAL (median fold) | TOTAL (full history) | total ÷ typical |",
                "|---|--:|--:|--:|"]
    for r in rows:
        try:
            med = float(r["median_pnl"]); tot = float(r["full_pnl"])
            tf_table.append(f"| {r['tf']} | ${med:,.0f} | ${tot:,.0f} | {tot/med:.1f}× |")
        except (ValueError, KeyError, ZeroDivisionError):
            continue

    mermaid = ["```mermaid", "flowchart TD",
               "  H[Full history: Jan 2025 → May 2026<br/>~1.4 years of 4h bars] --> S{Two different lenses}",
               "  S --> W[**TYPICAL** lens:<br/>cut history into 5 equal time slices]",
               "  W --> F0[fold 0<br/>warmup — NOT scored]",
               "  W --> F1[fold 1]; W --> F2[fold 2]; W --> F3[fold 3]; W --> F4[fold 4]",
               "  F1 & F2 & F3 & F4 --> MED[take the MIDDLE fold's profit<br/>= median = 'typical']",
               "  S --> T[**TOTAL** lens:<br/>ONE continuous backtest over the WHOLE 1.4 years]",
               "  T --> TOT[cumulative profit at the end<br/>= 'total'<br/>breaker + equity carry across the whole line]",
               "```"]

    doc = f"""---
name: typical-vs-total-profit
description: Plain-language, detailed explainer of "typical profit" (median walk-forward fold P/L)
  vs "total profit" (full-history P/L) in the WS-I results, with the real 4h champion numbers,
  inline Plotly + Mermaid. Generated by docs/charts/build_profit_doc.py.
type: reference
status: generated
workstream: WS-I
---

# Typical profit vs Total profit — what's the difference? 🍼

In the WS-I results you see two money columns per strategy: **"typical profit"** and **"total
profit over all history."** They measure *different things* and are **not** versions of the same
number. This doc explains exactly what each one is, why they differ, and how to read them together.

---

## 1. The one-paragraph answer

- **Total profit** = run the strategy **once, straight through the entire history** (Jan 2025 →
  May 2026, ~1.4 years) and read the final cumulative profit. It's the **headline** number — "how
  much money would this have made, start to finish."
- **Typical profit** = chop that same history into **5 equal time-slices ("folds")**, score the
  strategy **separately** on each, and report the **median** (middle) slice's profit. It answers a
  *different* question — "in a **normal stretch**, not a lucky one, what does a slice earn?" It's a
  **robustness / consistency** number, deliberately blind to the single best and single worst slice.

One is *cumulative over everything*; the other is *the middle of several independent chunks*.

---

## 2. Why two numbers at all?

Because a single big total can lie. A strategy can post a huge total profit on the back of **one
freak winning stretch** while losing or flat-lining the rest of the time — that's the classic
shape of an **overfit** strategy that won't repeat. The median-fold ("typical") number is the
antidote: if four independent slices all look healthy, the edge is more likely *real* and
*repeatable*, not a one-off.

So we optimise for **typical** (consistency) and report **total** (headline) — and we get nervous
when the two disagree wildly.

---

## 3. The real example — the 4h champion

Here are the **actual** numbers for the 4h winning strategy. Its 1.4-year history splits into 5
folds; fold 0 is a warm-up (used only to calibrate the volatility gate, never scored), folds 1–4
are scored:

{f1}

<sub>📊 each bar is the profit of one ~3-month slice. The green dashed line is their median — the
**typical** profit.</sub>

- Fold profits: **−$4,738 · $23,267 · $43,350 · $25,238**
- **Typical profit = median of those four = $24,253.** (The middle of the pack — it ignores the
  unlucky −$4.7k fold *and* the lucky $43k fold.)
- **Total profit = $56,040** — the single continuous run over all 1.4 years (including the warm-up
  period that the folds skip).

---

## 4. The trap: "shouldn't total = typical × 5?" — No.

Five folds, so you'd expect total ≈ 5 × typical, or at least total ≈ the sum of the folds. **Neither
holds**, and that's not a bug:

{f2}

The sum of the four folds is **${SUM_FOLDS:,.0f}**, yet the total is only **${TOTAL:,.0f}**. Three
reasons they diverge:

1. **The warm-up fold is in the total but not the typical.** Fold 0 (Jan–Apr 2025) is excluded from
   the median calculation but *is* part of the one continuous full-history run. Its profit (good or
   bad) lands in the total only.
2. **The drawdown breaker carries state in the total run, but resets each fold.** In the single
   continuous run, one bad drawdown can trip the circuit-breaker and **lock out trades** that an
   isolated fold (starting fresh) would happily have taken. So the continuous run is usually *more
   conservative* than the folds added up.
3. **The volatility gate is calibrated differently.** Each fold freezes its gate threshold on the
   data *before that fold*; the full run freezes it once on 2025. Different gates → slightly
   different trades taken.

**Takeaway:** they're two camera angles on the same strategy, not a number and its multiple. Don't
try to reconcile them arithmetically.

---

## 5. How the two are computed (precise)

```mermaid
{chr(10).join(mermaid[1:-1])}
```

| | **Typical profit** | **Total profit** |
|---|---|---|
| Code | `median_pnl` from `score_walkforward()` | `full_pnl` from `backtest_metrics(window="full")` |
| Span | median of folds 1–4 (each ≈ 3 months) | the entire history in one run (~1.4 yr) |
| Breaker/equity | resets per fold | carries across the whole timeline |
| Gate threshold | frozen on each fold's own past | frozen once on 2025 |
| Question it answers | "is the edge **consistent**?" | "what's the **headline** total?" |
| Role in the search | **optimisation objective** (maximise) | **feasibility check** (DD ≤ 25% of it) |

---

## 6. Every timeframe's two numbers

{chr(10).join(tf_table)}

<sub>The ratio wanders (some TFs ~2×, some higher) for exactly the reasons in §4 — it is **not**
meant to be 5×. A very high ratio with a low typical is a flag to inspect the per-fold spread for
one-lucky-fold overfitting.</sub>

---

## 7. How to read them together (cheat-sheet)

- **High typical + high total** → consistent *and* big. The best case. (4h: $24k typical, $56k total.)
- **Low/negative typical + high total** → ⚠️ probably **one lucky fold** carrying it. Treat with
  suspicion; check the per-fold bars before trusting.
- **High typical + modest total** → consistent but the breaker/warm-up dragged the continuous run;
  usually a *safe* sign (the strategy is steady, the breaker is protecting it).
- **Both low** → weak edge.

When in doubt, the **typical (median-fold)** number is the more trustworthy guide to whether an edge
will survive into the future; the **total** is the headline you'd quote for the full backtest.

---

_Generated by `docs/charts/build_profit_doc.py`. Fold numbers recomputed from `optimize/studies/wsh.db`
(the 4h champion); per-TF table from `optimize/results/wsi_leaderboard.csv`._
"""
    out = os.path.join(_DOCS, "TYPICAL_VS_TOTAL_PROFIT.md")
    open(out, "w").write(doc)
    print(f"wrote {os.path.relpath(out, _ROOT)} ({os.path.getsize(out)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
