"""Assemble ONE self-contained mega doc: the three WS-I reference docs concatenated, with the
Plotly charts embedded INLINE (not just linked) and the Mermaid diagrams kept.

Output: docs/WS-I_MEGADOC.md
  • Plotly figures are inlined as raw-HTML <div> (plotly.js via CDN, loaded once) — they render in
    VS Code preview / mkdocs / pandoc / a browser. A fallback link to the standalone html is kept so
    they still open on GitHub (which strips inline <script>). Mermaid ```mermaid fences render on
    GitHub + VS Code natively.

Run:  python3 subprojects/Parametric-Indicators/docs/charts/build_megadoc.py
"""
from __future__ import annotations

import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_DOCS = os.path.abspath(os.path.join(_HERE, ".."))
sys.path.insert(0, _HERE)

import make_charts as mc  # noqa: E402

# chart filename -> (builder, include the plotly.js cdn on this one?)
_BUILDERS = [
    ("votes_distribution.html", mc.votes_distribution),
    ("engine_vs_fast.html", mc.engine_vs_fast),
    ("nsga3_feasibility.html", mc.nsga3_feasibility),
    ("nsga3_objectives_3d.html", mc.nsga3_objectives_3d),
]
SOURCES = ["INDICATOR_LOGIC.md", "VECTORIZATION.md", "NSGA3.md"]


def _divs():
    """name -> inline <div> html. First chart carries the plotly.js CDN <script>."""
    out = {}
    for i, (name, fn) in enumerate(_BUILDERS):
        fig = fn()
        if fig is None:
            out[name] = f"<!-- chart {name} unavailable (no data) -->"
            continue
        out[name] = fig.to_html(full_html=False,
                                include_plotlyjs=("cdn" if i == 0 else False),
                                default_width="100%", default_height="460px")
    return out


def _strip_frontmatter(md: str) -> str:
    if md.startswith("---"):
        return md.split("\n---\n", 1)[1].lstrip("\n") if "\n---\n" in md else md
    return md


def _inline_charts(md: str, divs: dict) -> str:
    """Replace each '> 📊 ...charts/X.html...' blockquote with the inline div(s) + a fallback link."""
    # a blockquote block = consecutive lines starting with '>'
    def repl(m):
        block = m.group(0)
        names = list(dict.fromkeys(re.findall(r"charts/([\w.]+\.html)", block)))  # dedupe (link label+href)
        if not names:
            return block
        parts = []
        for n in names:
            parts.append(divs.get(n, f"<!-- {n} -->"))
            parts.append(f"\n\n<sub>📊 standalone: [`charts/{n}`](charts/{n})</sub>\n")
        return "\n".join(parts)
    return re.sub(r"(?:^> .*\n?)+", repl, md, flags=re.MULTILINE)


def main():
    divs = _divs()
    head = (
        "---\n"
        "name: ws-i-megadoc\n"
        "description: WS-I mega documentation — indicator logic + vectorization + NSGA-III in one "
        "self-contained file, with inline Plotly charts and Mermaid diagrams. Generated by "
        "docs/charts/build_megadoc.py (do not hand-edit).\n"
        "type: reference\nstatus: generated\nworkstream: WS-I\n---\n\n"
        "# WS-I — Mega Documentation (indicators · vectorization · NSGA-III)\n\n"
        "> **Generated** by `docs/charts/build_megadoc.py` — combines `INDICATOR_LOGIC.md`, "
        "`VECTORIZATION.md`, `NSGA3.md` with the Plotly charts inlined (CDN plotly.js) and Mermaid "
        "diagrams. Mermaid renders on GitHub/VS Code; the inline Plotly renders in VS Code preview / "
        "mkdocs / a browser (a standalone-chart link is kept as a GitHub fallback).\n\n"
        "**Contents:** [1 · Indicator logic](#indicator-logic--the-15-judges-golf) · "
        "[2 · Vectorization](#vectorization--turning-the-minute-loop-backtest-into-numpy-scans) · "
        "[3 · NSGA-III](#nsga-iii--many-objective-search-for-the-indicator-layer)\n\n---\n\n"
    )
    chunks = [head]
    for i, src in enumerate(SOURCES):
        md = _strip_frontmatter(open(os.path.join(_DOCS, src)).read())
        md = _inline_charts(md, divs)
        chunks.append(md.rstrip() + "\n")
        if i < len(SOURCES) - 1:
            chunks.append("\n\n---\n\n")
    out = os.path.join(_DOCS, "WS-I_MEGADOC.md")
    open(out, "w").write("\n".join(chunks))
    sz = os.path.getsize(out)
    print(f"wrote {os.path.relpath(out, os.path.dirname(_DOCS))}  ({sz/1024:.0f} KB)")


if __name__ == "__main__":
    main()
