"""Group C — ICT / Smart-Money-Concept structure detectors (causal, no look-ahead).

These are the OHLC-derived structures generated by the two-phase pipeline (decision #11). FVG uses
wick geometry; structure/golf use closes/bodies per the frozen spec. Order-block/breaker (a stateful
machine over structure) builds on market_structure and lands in a later increment.

STUBS first (TDD: tests/test_smc.py).
"""
from __future__ import annotations

import numpy as np


def fvg(high: np.ndarray, low: np.ndarray):
    """3-candle Fair Value Gap (wick-based). At bar t (the 3rd candle):
      bullish iff low[t] > high[t-2]  → zone [high[t-2], low[t]]
      bearish iff high[t] < low[t-2]  → zone [high[t],   low[t-2]]
    Returns (bull, bear, zone_lo, zone_hi): bull/bear bool arrays; zone_lo/hi float (NaN if none)."""
    h = np.asarray(high, float); l = np.asarray(low, float)
    n = len(h)
    bull = np.zeros(n, bool); bear = np.zeros(n, bool)
    zlo = np.full(n, np.nan); zhi = np.full(n, np.nan)
    for t in range(2, n):
        if l[t] > h[t - 2]:
            bull[t] = True; zlo[t] = h[t - 2]; zhi[t] = l[t]
        elif h[t] < l[t - 2]:
            bear[t] = True; zlo[t] = h[t]; zhi[t] = l[t - 2]
    return bull, bear, zlo, zhi


def market_structure(close: np.ndarray, swing_l: int = 2):
    """Close-based fractal swings. swing_high[t]=True iff close[t] strictly exceeds the swing_l
    closes on BOTH sides; mirror for swing_low. (Pivot index marked; confirmation timing is the
    consumer's job — a pivot is only knowable swing_l bars later.) Returns (swing_high, swing_low)."""
    c = np.asarray(close, float)
    n = len(c)
    sh = np.zeros(n, bool); sl = np.zeros(n, bool)
    L = int(swing_l)
    for t in range(L, n - L):
        left = c[t - L:t]
        right = c[t + 1:t + 1 + L]
        if (c[t] > left).all() and (c[t] > right).all():
            sh[t] = True
        if (c[t] < left).all() and (c[t] < right).all():
            sl[t] = True
    return sh, sl


def fvg_active_direction(high: np.ndarray, low: np.ndarray, lookback: int = 3) -> np.ndarray:
    """Per-bar directional bias from the most recent FVG within `lookback` bars: +1 if the latest
    FVG (within lookback) is bullish, -1 bearish, 0 if none recent. The retrace-into-zone entry is
    handled by the indicator's retrace param + the engine resolver; this is the directional read."""
    bull, bear, _, _ = fvg(high, low)
    n = len(bull)
    out = np.zeros(n, dtype=np.int8)
    last_dir = 0
    last_idx = -10 ** 9
    for t in range(n):
        if bull[t]:
            last_dir, last_idx = 1, t
        elif bear[t]:
            last_dir, last_idx = -1, t
        if last_dir != 0 and (t - last_idx) <= lookback:
            out[t] = last_dir
    return out


def structure_trend(close: np.ndarray, swing_l: int = 2) -> np.ndarray:
    """Per-bar trend stance from confirmed swing structure (causal). A swing pivot at index p is
    only known swing_l bars later. stance[t] = +1 when the latest two confirmed swing highs are
    rising AND the latest two confirmed swing lows are rising (HH+HL uptrend); -1 for LH+LL; the
    stance is carried forward between structure updates; 0 until enough swings exist."""
    c = np.asarray(close, float)
    n = len(c)
    sh, sl = market_structure(c, swing_l)
    L = int(swing_l)
    out = np.zeros(n, dtype=np.int8)
    highs, lows = [], []
    cur = 0
    for t in range(n):
        p = t - L
        if p >= 0:
            if sh[p]:
                highs.append(c[p])
            if sl[p]:
                lows.append(c[p])
        if len(highs) >= 2 and len(lows) >= 2:
            hh, hl = highs[-1] > highs[-2], lows[-1] > lows[-2]
            lh, ll = highs[-1] < highs[-2], lows[-1] < lows[-2]
            if hh and hl:
                cur = 1
            elif lh and ll:
                cur = -1
            # else: carry the prior stance
        out[t] = cur
    return out


def order_blocks(open_, high, low, close, swing_l: int = 2):
    """Causal order-block detection. A bullish OB = the last down-close candle before a close that
    breaks ABOVE the most recent confirmed swing high; bearish OB = last up-close candle before a
    close breaking BELOW the most recent confirmed swing low. Once price CLOSES beyond an OB it
    converts to a breaker (role flips) and is no longer usable as an OB.

    Returns ob_signal: per-bar int8 ∈ {+1,-1,0} — +1 while price trades within a live BULLISH OB
    zone (a long-reaction zone), -1 within a live BEARISH OB zone, else 0.
    """
    o = np.asarray(open_, float); h = np.asarray(high, float)
    l = np.asarray(low, float); c = np.asarray(close, float)
    n = len(c)
    sh, sl = market_structure(c, swing_l)
    L = int(swing_l)
    out = np.zeros(n, dtype=np.int8)
    swh = swl = None
    last_down = last_up = None
    bull, bear = [], []           # active zones [lo, hi]
    prev_above = prev_below = False
    for t in range(n):
        p = t - L
        if p >= 0:
            if sh[p]:
                swh = c[p]
            if sl[p]:
                swl = c[p]
        # fresh break above the latest swing high → bullish OB at the last down-close candle
        if swh is not None:
            above = c[t] > swh
            if above and not prev_above and last_down is not None:
                bull.append([min(o[last_down], c[last_down]), max(o[last_down], c[last_down])])
            prev_above = above
        if swl is not None:
            below = c[t] < swl
            if below and not prev_below and last_up is not None:
                bear.append([min(o[last_up], c[last_up]), max(o[last_up], c[last_up])])
            prev_below = below
        # per-bar reaction signal: overlap with a live zone (bull preferred)
        s = 0
        for z in bull:
            if l[t] <= z[1] and h[t] >= z[0]:
                s = 1; break
        if s == 0:
            for z in bear:
                if l[t] <= z[1] and h[t] >= z[0]:
                    s = -1; break
        out[t] = s
        # conversion to breaker (burned into): bull OB dies on a close below it; bear on close above
        bull = [z for z in bull if not (c[t] < z[0])]
        bear = [z for z in bear if not (c[t] > z[1])]
        # track last opposite-close candle AFTER using prior state
        if c[t] < o[t]:
            last_down = t
        elif c[t] > o[t]:
            last_up = t
    return out


def golf_candle(open_: np.ndarray, close: np.ndarray, golf_n: int = 3) -> np.ndarray:
    """A 'golf' candle has body |close-open| greater than the max body of the prior golf_n candles.
    NaN/False for the first golf_n bars. Returns a bool array."""
    o = np.asarray(open_, float); c = np.asarray(close, float)
    body = np.abs(c - o)
    n = len(c)
    out = np.zeros(n, bool)
    m = int(golf_n)
    for t in range(m, n):
        out[t] = body[t] > body[t - m:t].max()
    return out
