"""Group C — ICT / Smart-Money-Concept structure detectors (causal, no look-ahead).

These are the OHLC-derived structures generated by the two-phase pipeline (decision #11). FVG uses
wick geometry; structure/golf use closes/bodies per the frozen spec. Order-block/breaker (a stateful
machine over structure) builds on market_structure and lands in a later increment.

STUBS first (TDD: tests/test_smc.py).
"""
from __future__ import annotations

import numpy as np


def fvg(high: np.ndarray, low: np.ndarray):
    """3-candle Fair Value Gap (wick-based). At bar t (the 3rd candle):
      bullish iff low[t] > high[t-2]  → zone [high[t-2], low[t]]
      bearish iff high[t] < low[t-2]  → zone [high[t],   low[t-2]]
    Returns (bull, bear, zone_lo, zone_hi): bull/bear bool arrays; zone_lo/hi float (NaN if none)."""
    h = np.asarray(high, float); l = np.asarray(low, float)
    n = len(h)
    bull = np.zeros(n, bool); bear = np.zeros(n, bool)
    zlo = np.full(n, np.nan); zhi = np.full(n, np.nan)
    for t in range(2, n):
        if l[t] > h[t - 2]:
            bull[t] = True; zlo[t] = h[t - 2]; zhi[t] = l[t]
        elif h[t] < l[t - 2]:
            bear[t] = True; zlo[t] = h[t]; zhi[t] = l[t - 2]
    return bull, bear, zlo, zhi


def market_structure(close: np.ndarray, swing_l: int = 2):
    """Close-based fractal swings. swing_high[t]=True iff close[t] strictly exceeds the swing_l
    closes on BOTH sides; mirror for swing_low. (Pivot index marked; confirmation timing is the
    consumer's job — a pivot is only knowable swing_l bars later.) Returns (swing_high, swing_low)."""
    c = np.asarray(close, float)
    n = len(c)
    sh = np.zeros(n, bool); sl = np.zeros(n, bool)
    L = int(swing_l)
    for t in range(L, n - L):
        left = c[t - L:t]
        right = c[t + 1:t + 1 + L]
        if (c[t] > left).all() and (c[t] > right).all():
            sh[t] = True
        if (c[t] < left).all() and (c[t] < right).all():
            sl[t] = True
    return sh, sl


def fvg_active_direction(high: np.ndarray, low: np.ndarray, lookback: int = 3) -> np.ndarray:
    """Per-bar directional bias from the most recent FVG within `lookback` bars: +1 if the latest
    FVG (within lookback) is bullish, -1 bearish, 0 if none recent. The retrace-into-zone entry is
    handled by the indicator's retrace param + the engine resolver; this is the directional read."""
    bull, bear, _, _ = fvg(high, low)
    n = len(bull)
    out = np.zeros(n, dtype=np.int8)
    last_dir = 0
    last_idx = -10 ** 9
    for t in range(n):
        if bull[t]:
            last_dir, last_idx = 1, t
        elif bear[t]:
            last_dir, last_idx = -1, t
        if last_dir != 0 and (t - last_idx) <= lookback:
            out[t] = last_dir
    return out


def structure_trend(close: np.ndarray, swing_l: int = 2) -> np.ndarray:
    """Per-bar trend stance from confirmed swing structure (causal). A swing pivot at index p is
    only known swing_l bars later. stance[t] = +1 when the latest two confirmed swing highs are
    rising AND the latest two confirmed swing lows are rising (HH+HL uptrend); -1 for LH+LL; the
    stance is carried forward between structure updates; 0 until enough swings exist."""
    c = np.asarray(close, float)
    n = len(c)
    sh, sl = market_structure(c, swing_l)
    L = int(swing_l)
    out = np.zeros(n, dtype=np.int8)
    highs, lows = [], []
    cur = 0
    for t in range(n):
        p = t - L
        if p >= 0:
            if sh[p]:
                highs.append(c[p])
            if sl[p]:
                lows.append(c[p])
        if len(highs) >= 2 and len(lows) >= 2:
            hh, hl = highs[-1] > highs[-2], lows[-1] > lows[-2]
            lh, ll = highs[-1] < highs[-2], lows[-1] < lows[-2]
            if hh and hl:
                cur = 1
            elif lh and ll:
                cur = -1
            # else: carry the prior stance
        out[t] = cur
    return out


def order_blocks(open_, high, low, close, swing_l: int = 2, signal_at=None):
    """Causal order-block detection. A bullish OB = the last down-close candle before a close that
    breaks ABOVE the most recent confirmed swing high; bearish OB = last up-close candle before a
    close breaking BELOW the most recent confirmed swing low. Once price CLOSES beyond an OB it
    converts to a breaker (role flips) and is no longer usable as an OB.

    Returns ob_signal: per-bar int8 ∈ {+1,-1,0} — +1 while price trades within a live BULLISH OB
    zone (a long-reaction zone), -1 within a live BEARISH OB zone, else 0.

    signal_at (task #210, Step E): an optional array of bar indices whose output value will actually be
    READ (the decision bars' sampled 1-minute candles). When given, the per-bar OVERLAP signal is
    computed ONLY at those indices (the zone STATE — swings, breaks, pruning — still advances every bar,
    so the value at each requested index is identical to the full computation); other bars stay 0 and
    are never read. signal_at=None ⇒ compute every bar (the original behaviour, used by the decision-TF
    path + parity tests). Frozen reference: indicators/_reference.order_blocks_ref.
    """
    o = np.asarray(open_, float); h = np.asarray(high, float)
    l = np.asarray(low, float); c = np.asarray(close, float)
    n = len(c)
    sh, sl = market_structure(c, swing_l)
    L = int(swing_l)
    out = np.zeros(n, dtype=np.int8)
    want = None
    if signal_at is not None:
        want = np.zeros(n, dtype=bool)
        idx = np.asarray(signal_at, dtype=np.intp)
        want[idx[(idx >= 0) & (idx < n)]] = True
    swh = swl = None
    last_down = last_up = None
    # Live zones as numpy arrays (lo, hi) instead of Python lists (task #210, Step C′). Appends (on
    # breaks) are rare; the per-bar overlap (np.any) and pruning (boolean mask) are VECTORISED — exactly
    # the same operations as the list version, at C speed. Output is unchanged (proven bit-identical vs
    # _reference.order_blocks_ref). signal_at gating (Step E) is preserved.
    bull_lo = np.empty(0, dtype=float); bull_hi = np.empty(0, dtype=float)
    bear_lo = np.empty(0, dtype=float); bear_hi = np.empty(0, dtype=float)
    prev_above = prev_below = False
    for t in range(n):
        p = t - L
        if p >= 0:
            if sh[p]:
                swh = c[p]
            if sl[p]:
                swl = c[p]
        # fresh break above the latest swing high → bullish OB at the last down-close candle
        if swh is not None:
            above = c[t] > swh
            if above and not prev_above and last_down is not None:
                lo = min(o[last_down], c[last_down]); hi = max(o[last_down], c[last_down])
                bull_lo = np.append(bull_lo, lo); bull_hi = np.append(bull_hi, hi)
            prev_above = above
        if swl is not None:
            below = c[t] < swl
            if below and not prev_below and last_up is not None:
                lo = min(o[last_up], c[last_up]); hi = max(o[last_up], c[last_up])
                bear_lo = np.append(bear_lo, lo); bear_hi = np.append(bear_hi, hi)
            prev_below = below
        # per-bar reaction signal: overlap with a live zone (bull preferred). Skipped where the value is
        # never read (want[t] False) — out[t] stays 0; the state updates below STILL run every bar.
        if want is None or want[t]:
            s = 0
            if bull_lo.size and np.any((l[t] <= bull_hi) & (h[t] >= bull_lo)):
                s = 1
            elif bear_lo.size and np.any((l[t] <= bear_hi) & (h[t] >= bear_lo)):
                s = -1
            out[t] = s
        # conversion to breaker (burned into): bull OB dies on a close BELOW it (keep lo ≤ c[t]); bear on
        # a close ABOVE it (keep hi ≥ c[t]). Realloc only when something actually drops out.
        if bull_lo.size:
            keep = bull_lo <= c[t]
            if not keep.all():
                bull_lo = bull_lo[keep]; bull_hi = bull_hi[keep]
        if bear_lo.size:
            keep = bear_hi >= c[t]
            if not keep.all():
                bear_lo = bear_lo[keep]; bear_hi = bear_hi[keep]
        # track last opposite-close candle AFTER using prior state
        if c[t] < o[t]:
            last_down = t
        elif c[t] > o[t]:
            last_up = t
    return out


def swing_labels(close: np.ndarray, swing_l: int = 2):
    """Label every confirmed close-based swing pivot as HH / LH (highs) or HL / LL (lows).

    Built on `market_structure` (a pivot at index p is only knowable swing_l bars later). Each swing HIGH
    is compared to the PRIOR swing high → 'HH' if higher else 'LH'; each swing LOW to the prior swing low →
    'HL' if higher else 'LL'. The first high/low has no prior → '' (the study marks it FIRST). Causal: the
    comparison at pivot p uses only earlier pivots.

    Returns (kind, label, confirmed_at):
      kind        int8  +1 at a swing-high bar, -1 at a swing-low bar, 0 otherwise
      label       object  'HH'|'LH'|'HL'|'LL'|'' (non-empty only at pivot bars)
      confirmed_at int   p + swing_l (the bar at which the pivot becomes knowable), -1 off-pivot
    """
    c = np.asarray(close, float)
    n = len(c)
    sh, sl = market_structure(c, swing_l)
    L = int(swing_l)
    kind = np.zeros(n, np.int8)
    label = np.full(n, "", dtype=object)
    confirmed_at = np.full(n, -1, dtype=int)
    last_high = last_low = None
    for p in range(n):                                   # pivots in chronological (index) order
        if sh[p]:
            kind[p] = 1
            label[p] = ("HH" if c[p] > last_high else "LH") if last_high is not None else ""
            last_high = c[p]; confirmed_at[p] = p + L
        elif sl[p]:
            kind[p] = -1
            label[p] = ("HL" if c[p] > last_low else "LL") if last_low is not None else ""
            last_low = c[p]; confirmed_at[p] = p + L
    return kind, label, confirmed_at


def ifvg(high: np.ndarray, low: np.ndarray, close: np.ndarray, signal_at=None) -> np.ndarray:
    """Inverse Fair Value Gap (causal). An FVG that price CLOSES through inverts and becomes an opposing
    S/R zone (the 'burned-into' flip):
      • bullish FVG [zlo,zhi] (support) → bearish IFVG (resistance) once a close < zlo;
      • bearish FVG [zlo,zhi] (resistance) → bullish IFVG (support) once a close > zhi.
    Per-bar signal int8: +1 while the current bar overlaps a live BULLISH IFVG (support), -1 a live BEARISH
    IFVG (resistance), else 0. A live IFVG dies when price closes back through it (bull IFVG: close < zlo;
    bear IFVG: close > zhi). Trigger = a CLOSE (locked decision A4). signal_at as in `order_blocks`."""
    h = np.asarray(high, float); l = np.asarray(low, float); c = np.asarray(close, float)
    n = len(c)
    out = np.zeros(n, np.int8)
    want = None
    if signal_at is not None:
        want = np.zeros(n, bool); idx = np.asarray(signal_at, dtype=np.intp)
        want[idx[(idx >= 0) & (idx < n)]] = True
    fvgs = []                                            # live, un-inverted FVGs: [zlo, zhi, dir]
    ifvgs = []                                           # live inverse zones: [zlo, zhi, dir(flipped)]
    for t in range(n):
        # 1) form a new FVG at the 3rd candle (uses t, t-2 only)
        if t >= 2:
            if l[t] > h[t - 2]:
                fvgs.append([h[t - 2], l[t], 1])
            elif h[t] < l[t - 2]:
                fvgs.append([h[t], l[t - 2], -1])
        # 2) invert FVGs that this close burned through; drop them from the live-FVG list
        keep = []
        for zlo, zhi, d in fvgs:
            if d == 1 and c[t] < zlo:
                ifvgs.append([zlo, zhi, -1])             # bullish FVG failed → bearish IFVG
            elif d == -1 and c[t] > zhi:
                ifvgs.append([zlo, zhi, 1])              # bearish FVG failed → bullish IFVG
            else:
                keep.append([zlo, zhi, d])
        fvgs = keep
        # 3) per-bar signal from live IFVGs (overlap with current bar); bull preferred
        if want is None or want[t]:
            s = 0
            for zlo, zhi, d in ifvgs:
                if l[t] <= zhi and h[t] >= zlo:
                    s = d;
                    if d == 1:
                        break
            out[t] = s
        # 4) IFVG death: price closes back through it
        ifvgs = [[zlo, zhi, d] for zlo, zhi, d in ifvgs
                 if not ((d == 1 and c[t] < zlo) or (d == -1 and c[t] > zhi))]
    return out


def breaker_blocks(open_, high, low, close, swing_l: int = 2, signal_at=None) -> np.ndarray:
    """Tradeable BREAKER blocks (causal). An order block that price CLOSES beyond is retired as an OB and
    flips role/colour into a breaker, then acts as an ENTRY zone in the FLIPPED direction (locked A9):
      • bullish OB (support) broken by a close BELOW it → BEARISH breaker (resistance / short zone);
      • bearish OB (resistance) broken by a close ABOVE it → BULLISH breaker (support / long zone).
    (Matches the user's colour-flip: top OB red→top breaker green is the bearish-OB→bullish-breaker case.)
    Per-bar signal int8: +1 within a live bullish breaker, -1 within a live bearish breaker, else 0. A
    breaker dies when price closes back through it. OB geometry = body (open,close), as in `order_blocks`."""
    o = np.asarray(open_, float); h = np.asarray(high, float)
    l = np.asarray(low, float); c = np.asarray(close, float)
    n = len(c)
    sh, sl = market_structure(c, swing_l)
    L = int(swing_l)
    out = np.zeros(n, np.int8)
    want = None
    if signal_at is not None:
        want = np.zeros(n, bool); idx = np.asarray(signal_at, dtype=np.intp)
        want[idx[(idx >= 0) & (idx < n)]] = True
    swh = swl = None
    last_down = last_up = None
    bull_ob = []                                         # live bullish OBs: [lo, hi]
    bear_ob = []                                         # live bearish OBs: [lo, hi]
    breakers = []                                        # live breakers: [lo, hi, dir]
    prev_above = prev_below = False
    for t in range(n):
        p = t - L
        if p >= 0:
            if sh[p]:
                swh = c[p]
            if sl[p]:
                swl = c[p]
        if swh is not None:
            above = c[t] > swh
            if above and not prev_above and last_down is not None:
                bull_ob.append([min(o[last_down], c[last_down]), max(o[last_down], c[last_down])])
            prev_above = above
        if swl is not None:
            below = c[t] < swl
            if below and not prev_below and last_up is not None:
                bear_ob.append([min(o[last_up], c[last_up]), max(o[last_up], c[last_up])])
            prev_below = below
        # OB → breaker conversion on a close beyond the OB (role + direction flip)
        keep_bull = []
        for lo, hi in bull_ob:
            if c[t] < lo:
                breakers.append([lo, hi, -1])            # bullish OB broken down → bearish breaker
            else:
                keep_bull.append([lo, hi])
        bull_ob = keep_bull
        keep_bear = []
        for lo, hi in bear_ob:
            if c[t] > hi:
                breakers.append([lo, hi, 1])             # bearish OB broken up → bullish breaker
            else:
                keep_bear.append([lo, hi])
        bear_ob = keep_bear
        # per-bar breaker reaction signal (overlap), bull preferred
        if want is None or want[t]:
            s = 0
            for lo, hi, d in breakers:
                if l[t] <= hi and h[t] >= lo:
                    s = d
                    if d == 1:
                        break
            out[t] = s
        # breaker death: price closes back through it
        breakers = [[lo, hi, d] for lo, hi, d in breakers
                    if not ((d == 1 and c[t] < lo) or (d == -1 and c[t] > hi))]
        if c[t] < o[t]:
            last_down = t
        elif c[t] > o[t]:
            last_up = t
    return out


def cisd(open_: np.ndarray, close: np.ndarray) -> np.ndarray:
    """CISD — Change In State of Delivery (STANDARD definition, locked A10). A 'delivery leg' is a run of
    consecutive same-colour candles; its reference level is the OPEN of the FIRST candle in the run. When a
    later candle CLOSES back through that open in the opposite direction, the state of delivery has changed:
      • bearish CISD (-1): a close BELOW the open of the most recent BULLISH (green) leg;
      • bullish CISD (+1): a close ABOVE the open of the most recent BEARISH (red) leg.
    Per-bar signal int8 ∈ {+1,-1,0}; fires on the bar that closes through. Causal (≤ t data only)."""
    o = np.asarray(open_, float); c = np.asarray(close, float)
    n = len(c)
    out = np.zeros(n, np.int8)
    bull_open = bear_open = None                          # open of the start of the latest green / red run
    prev_color = 0
    for t in range(n):
        color = 1 if c[t] > o[t] else (-1 if c[t] < o[t] else 0)
        if color == 1 and prev_color != 1:
            bull_open = o[t]                              # new green run starts here
        elif color == -1 and prev_color != -1:
            bear_open = o[t]                              # new red run starts here
        if bull_open is not None and c[t] < bull_open:
            out[t] = -1                                   # closed through the bullish leg's open → bearish
        elif bear_open is not None and c[t] > bear_open:
            out[t] = 1                                    # closed through the bearish leg's open → bullish
        if color != 0:
            prev_color = color
    return out


def golf_candle(open_: np.ndarray, high: np.ndarray, low: np.ndarray, close: np.ndarray,
                golf_n: int = 3) -> np.ndarray:
    """'Golf' = an N-candle ENGULFING reversal (WS-I review #2). For bar t (t ≥ N), returns
    +1 bullish / -1 bearish / 0 none, where N = golf_n:

      1. opposite colour to ALL N prior candles —
           bullish: current green (close>open) AND every prior t-N..t-1 is red (close<open);
           bearish: current red          AND every prior t-N..t-1 is green;
      2. range engulf (wicks): current.high ≥ max(high[t-N:t]) AND current.low ≤ min(low[t-N:t]);
      3. body filter: |close-open| ≥ 0.70 × prior_span, prior_span = max(high[t-N:t]) − min(low[t-N:t]).

    First N bars are 0. Dojis (close==open) are neither red nor green ⇒ break the colour test.
    """
    o = np.asarray(open_, float); h = np.asarray(high, float)
    lo = np.asarray(low, float); c = np.asarray(close, float)
    n = len(c)
    m = int(golf_n)
    out = np.zeros(n, np.int8)
    body = np.abs(c - o)
    for t in range(m, n):
        ph = h[t - m:t].max(); pl = lo[t - m:t].min(); span = ph - pl
        if not ((h[t] >= ph) and (lo[t] <= pl) and (body[t] >= 0.70 * span)):
            continue                                   # need wick-engulf + body ≥ 70% of prior span
        prior_red = bool(np.all(c[t - m:t] < o[t - m:t]))
        prior_green = bool(np.all(c[t - m:t] > o[t - m:t]))
        if c[t] > o[t] and prior_red:                  # bullish engulfing
            out[t] = 1
        elif c[t] < o[t] and prior_green:              # bearish engulfing
            out[t] = -1
    return out
