"""WS-AS packager — lay one instrument's technical output tree into a logical
<TOKEN>_SIGNALS_DELIVERY/ bundle, mirroring NQ_SIGNALS_DELIVERY exactly.

Reads `output/<token>/<TF>/...` (produced by generate_signals.py) and builds, at the
repo root, `<token>_SIGNALS_DELIVERY/` with the 4 numbered folders + README + SUMMARY,
filenames `<token>_<TF>_<preset>.csv`. Optionally zips it for one-file handoff.

Usage:
    python3 subprojects/all-stocks-signals/package_delivery.py --instruments NQ
    python3 subprojects/all-stocks-signals/package_delivery.py            # all present
    python3 subprojects/all-stocks-signals/package_delivery.py --zip
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_HERE, '..', '..'))
sys.path.insert(0, _HERE)
from instruments import REGISTRY, TOKENS, TIMEFRAMES, PRESETS, Instrument  # noqa: E402

_OUT_ROOT = os.path.join(_HERE, 'output')


def _copy(src: str, dst: str, n: list) -> None:
    if not os.path.exists(src):
        print(f"  MISSING {src}", file=sys.stderr); return
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst); n[0] += 1


def _readme(inst: Instrument) -> str:
    tfs = ' '.join(f'{inst.token}_{tf}' for tf in TIMEFRAMES)
    return f"""# {inst.token} Signals — Delivery Bundle

Logically-organised clone of the {inst.token} full-candles signal outputs. Grouped by
**what each file is** (the product), with **timeframe** and **preset** encoded in the
filename — `{inst.token}_<TIMEFRAME>_<PRESET>.csv`, e.g. `{inst.token}_15m_2025.csv`.

Timeframes: `{tfs}`
Presets:    `full`, `2025`, `2026`

## Folders

| Folder | Contents |
|---|---|
| `1_all_signals/`          | Every (candle × box) pair labelled `long`/`short`/`hold`. The complete signal stream. |
| `2_holds_dropped/`        | The same rows with all `hold`s removed — only `long`/`short` signals, plus a `holds_dropped` column = how many `hold` rows were removed right before each signal. |
| `3_reverse_signals/`      | Reverse windows (long→…→short or short→…→long). Each row carries `window_high` (**max high**), `window_low` (**min low**), direction-aware `tp`/`sl`, and `holds_between`. |
| `4_reverse_by_direction/long_to_short/` | Reverse windows that opened `long`. |
| `4_reverse_by_direction/short_to_long/` | Reverse windows that opened `short`. |
| `SUMMARY.csv`             | Row/window counts for every (timeframe, preset). |
| `PAUSE_SUMMARY.json`/`.md`| Longest **box-only** pause per (timeframe, preset): max consecutive `hold` run in `1_all_signals`, the longest reverse-window pause, and `holds_dropped_total`. |

## Column schemas

**`1_all_signals`** (10 cols):
`datetime, open, high, low, close, volume, signal, box_id, box_upper, box_lower`

**`2_holds_dropped`** (11 cols): the above + `holds_dropped` (consecutive `hold` rows removed
immediately before each kept signal).

**`3_reverse_signals` & `4_reverse_by_direction`** (21 cols):
`first_datetime, first_open, first_high, first_low, first_close, first_signal,
first_box_id, first_box_type, last_datetime, last_open, last_high, last_low,
last_close, last_signal, last_box_id, last_box_type, window_high, window_low,
tp, sl, holds_between`

## Provenance

Generated by WS-AS (`subprojects/all-stocks-signals/`) reusing the FROZEN Stage 1 + Stage 2
rules verbatim — the identical methodology as `NQ_SIGNALS_DELIVERY` (the regenerated NQ bundle
is byte-identical to the committed original). Candles + boxes sourced from `ALL_STOCKS/` for
this instrument only (no cross-instrument mixing). Source candles: `{inst.candle_prefix}_<TF>.csv`;
boxes: `{os.path.relpath(inst.box_csv, _REPO_ROOT)}`.
Pipeline doc: `subprojects/signals/full_candles/docs/PIPELINE.md`.
"""


def build_one(inst: Instrument, make_zip: bool) -> int:
    token = inst.token
    src_root = os.path.join(_OUT_ROOT, token)
    if not os.path.isdir(src_root):
        print(f"  SKIP {token}: no output tree at {src_root}", file=sys.stderr); return 0
    dst = os.path.join(_REPO_ROOT, inst.delivery_name())
    if os.path.exists(dst):
        shutil.rmtree(dst)
    os.makedirs(dst)

    n = [0]
    for tf in TIMEFRAMES:
        tf_dir = os.path.join(src_root, tf)
        for preset in PRESETS:
            name = f'{token}_{tf}_{preset}.csv'
            _copy(os.path.join(tf_dir, f'signals_{token}_{tf}_{preset}.csv'),
                  os.path.join(dst, '1_all_signals', name), n)
            _copy(os.path.join(tf_dir, 'no_holds', f'signals_{token}_{tf}_{preset}_no_holds.csv'),
                  os.path.join(dst, '2_holds_dropped', name), n)
            _copy(os.path.join(tf_dir, f'reverse_signals_{token}_{tf}_{preset}.csv'),
                  os.path.join(dst, '3_reverse_signals', name), n)
            _copy(os.path.join(tf_dir, 'by_direction', f'long_to_short_{token}_{tf}_{preset}.csv'),
                  os.path.join(dst, '4_reverse_by_direction', 'long_to_short', name), n)
            _copy(os.path.join(tf_dir, 'by_direction', f'short_to_long_{token}_{tf}_{preset}.csv'),
                  os.path.join(dst, '4_reverse_by_direction', 'short_to_long', name), n)

    _copy(os.path.join(src_root, 'SUMMARY.csv'), os.path.join(dst, 'SUMMARY.csv'), n)
    # box-pause sidecar (entry-pause visibility): longest box-only pause per (tf, preset)
    _copy(os.path.join(src_root, 'PAUSE_SUMMARY.json'), os.path.join(dst, 'PAUSE_SUMMARY.json'), n)
    _copy(os.path.join(src_root, 'PAUSE_SUMMARY.md'), os.path.join(dst, 'PAUSE_SUMMARY.md'), n)
    with open(os.path.join(dst, 'README.md'), 'w') as f:
        f.write(_readme(inst))
    print(f"  {token}: copied {n[0]} CSVs -> {dst}")

    if make_zip:
        archive = shutil.make_archive(dst, 'zip', root_dir=_REPO_ROOT, base_dir=inst.delivery_name())
        print(f"  {token}: archive -> {archive}")
    return n[0]


def main() -> int:
    ap = argparse.ArgumentParser(description='Package per-instrument delivery bundles')
    ap.add_argument('--instruments', nargs='+', default=TOKENS, choices=TOKENS)
    ap.add_argument('--zip', action='store_true', help='also write a .zip per bundle')
    args = ap.parse_args()
    for tok in args.instruments:
        build_one(REGISTRY[tok], args.zip)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
